name: Lint Go Code
on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Setup linter
      #   uses: golangci/golangci-lint-action@v3

      # - name: Run Lint
      #   run: golangci-lint run
      # - name: Run Tests
      #   run: go test -v

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=cslemes_points-to-go
            -Dsonar.organization=cslemes
            -Dsonar.sources=.

      - name: Check Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: "Quality Gate Status value"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
