name: Lint Go Code
on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup linter
        uses: golangci/golangci-lint-action@v3

      - name: Run Lint
        run: golangci-lint run
      # - name: Run Tests
      #   run: go test -v

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          host: "https://sonarcloud.io"
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: ${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
